name: todo-tracks
modules:
  network:
    type: NETWORK
    networkModule:
      IPv4Range: "10.240.0.0/16"
      description: "Network for app"
  firewall:
    type: FIREWALL
    firewallModule:
      network: "network"
      sourceRanges: [ "0.0.0.0/0" ]
      allowed:
        - IPProtocol: "tcp"
          ports: ["22", "80", "8443", "8080"]
  todo:
    type: REPLICA_POOL
    replicaPoolModule:
      numReplicas: 1
      replicaPoolParams:
        v1beta1:
          baseInstanceName: "todos-instance"
          machineType: "n1-standard-1"
          zone: "us-central1-a"
          onHostMaintenance: TERMINATE
          networkInterfaces:
            - network: "network"
              accessConfigs:
                - name: External NAT
                  type: ONE_TO_ONE_NAT
          serviceAccounts:
            - email: default
              # TODO: Revise the scopes necessary for this instance.
              scopes: [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/compute",
                "https://www.googleapis.com/auth/datastore",
                "https://www.googleapis.com/auth/devstorage.full_control",
                "https://www.googleapis.com/auth/devstorage.read_write",
                "https://www.googleapis.com/auth/ndev.cloudman",
                "https://www.googleapis.com/auth/userinfo.email",
                "https://www.googleapis.com/auth/userinfo.profile",
              ]
          autoRestart: true
          initAction: install-todo
          disksToCreate:
            - boot: true
              autoDelete: true
              initializeParams:
                sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-7-wheezy-v20140828
                diskSizeGb: 50

actions:
  install-todo:
    # TODO: Figure out how to make pull app id by default.
    commands: [
      "apt-get -qqy update",
      # Install git from backport, base wheezy git is 1.7.x which isn't
      # compatible with gcloud init.
      "apt-get -qqy -t wheezy-backports install git",
      # Update to latest gcloud.
      "gcloud --quiet components update",
      "gcloud --quiet components update preview",
      # Initialize/clone git repo.
      "mkdir -p repo; cd repo; gcloud init todo-tracks",
      # Copy over todo binary from Google Cloud Storage bucket.
      # TODO: Considering using wget.
      "gsutil cp gs://todo-track-bin/todos /repo/todo-tracks/default/",
      # Set executable bit on todo binary.
      "chmod +x /repo/todo-tracks/default/todos",
      # Start running todo server.
      "cd /repo/todo-tracks/default; ./todos --todo_regex=\"TODO([(]|:)\" &",
      # Configure cronjob to pull git repo every minute.
      "echo \"* * * * * su -s /bin/sh root -c 'cd /repo/todo-tracks/default && /usr/bin/git pull'\" >> /tmp/crontab.txt",
      "crontab /tmp/crontab.txt"
    ]
