# Google Deployment Manager template for creating a todo tracker deployment in a project
# Usage:
# $ gcloud components update
# $ gcloud components update preview
# $ gcloud preview deployment-manager templates create todo_tracks_template --template-file config/gce.yaml
# $ gcloud preview deployment-manager deployments --region=us-central1 create --template=todo_tracks_template todo_tracks_deployment
name: todo-tracks
modules:
  network:
    type: NETWORK
    networkModule:
      IPv4Range: "10.240.0.0/16"
      description: "Network for app"
  firewall:
    type: FIREWALL
    firewallModule:
      network: "network"
      sourceRanges: [ "0.0.0.0/0" ]
      allowed:
        - IPProtocol: "tcp"
          ports: ["22", "80", "8443", "8080"]
  todo:
    type: REPLICA_POOL
    replicaPoolModule:
      numReplicas: 1
      replicaPoolParams:
        v1beta1:
          baseInstanceName: "todos-instance"
          machineType: "n1-standard-1"
          zone: "us-central1-a"
          onHostMaintenance: TERMINATE
          networkInterfaces:
            - network: "network"
              accessConfigs:
                - name: External NAT
                  type: ONE_TO_ONE_NAT
          serviceAccounts:
            - email: default
              scopes: [
                "https://www.googleapis.com/auth/cloud-platform",
              ]
          autoRestart: true
          initAction: install-todo
          disksToCreate:
            - boot: true
              autoDelete: true
              initializeParams:
                sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-7-wheezy-v20140828
                diskSizeGb: 50

actions:
  install-todo:
    commands: [
      "%file:gce.sh",
    ]
